export const LEVEL_CONFIGS = {
  subtraction: [
    { level: 1, maxNum: 5, choiceCount: 4 },
    { level: 2, maxNum: 8, choiceCount: 4 },
    { level: 3, maxNum: 10, choiceCount: 4 },
    { level: 4, maxNum: 15, choiceCount: 4 },
    { level: 5, maxNum: 20, choiceCount: 4 },
    { level: 6, maxNum: 30, choiceCount: 4 },
    { level: 7, maxNum: 50, choiceCount: 4 },
    { level: 8, maxNum: 75, choiceCount: 4 },
    { level: 9, maxNum: 100, choiceCount: 4 },
    { level: 10, maxNum: 100, choiceCount: 6 },
  ],
  addition: [
    { level: 1, maxNum: 5, choiceCount: 4 },
    { level: 2, maxNum: 8, choiceCount: 4 },
    { level: 3, maxNum: 10, choiceCount: 4 },
    { level: 4, maxNum: 15, choiceCount: 4 },
    { level: 5, maxNum: 20, choiceCount: 4 },
    { level: 6, maxNum: 30, choiceCount: 4 },
    { level: 7, maxNum: 50, choiceCount: 4 },
    { level: 8, maxNum: 75, choiceCount: 4 },
    { level: 9, maxNum: 100, choiceCount: 4 },
    { level: 10, maxNum: 100, choiceCount: 6 },
  ],
  'times-tables': [
    { level: 1, maxTable: 3, maxMultiplier: 5, choiceCount: 4 },
    { level: 2, maxTable: 5, maxMultiplier: 6, choiceCount: 4 },
    { level: 3, maxTable: 6, maxMultiplier: 8, choiceCount: 4 },
    { level: 4, maxTable: 7, maxMultiplier: 10, choiceCount: 4 },
    { level: 5, maxTable: 8, maxMultiplier: 10, choiceCount: 4 },
    { level: 6, maxTable: 9, maxMultiplier: 12, choiceCount: 4 },
    { level: 7, maxTable: 10, maxMultiplier: 15, choiceCount: 4 },
    { level: 8, maxTable: 11, maxMultiplier: 15, choiceCount: 4 },
    { level: 9, maxTable: 12, maxMultiplier: 20, choiceCount: 4 },
    { level: 10, maxTable: 12, maxMultiplier: 20, choiceCount: 6 },
  ],
  counting: [
    { level: 1, maxCount: 3, choiceCount: 4 },
    { level: 2, maxCount: 5, choiceCount: 4 },
    { level: 3, maxCount: 8, choiceCount: 4 },
    { level: 4, maxCount: 10, choiceCount: 4 },
    { level: 5, maxCount: 12, choiceCount: 4 },
    { level: 6, maxCount: 15, choiceCount: 4 },
    { level: 7, maxCount: 18, choiceCount: 4 },
    { level: 8, maxCount: 20, choiceCount: 4 },
    { level: 9, maxCount: 25, choiceCount: 4 },
    { level: 10, maxCount: 30, choiceCount: 6 },
  ],
  'color-match': [
    { level: 1, colorCount: 4, choiceCount: 2 },
    { level: 2, colorCount: 5, choiceCount: 3 },
    { level: 3, colorCount: 6, choiceCount: 3 },
    { level: 4, colorCount: 7, choiceCount: 4 },
    { level: 5, colorCount: 8, choiceCount: 4 },
    { level: 6, colorCount: 9, choiceCount: 4 },
    { level: 7, colorCount: 10, choiceCount: 5 },
    { level: 8, colorCount: 11, choiceCount: 5 },
    { level: 9, colorCount: 12, choiceCount: 6 },
    { level: 10, colorCount: 14, choiceCount: 6 },
  ],
  'shape-match': [
    { level: 1, shapeCount: 3, choiceCount: 2 },
    { level: 2, shapeCount: 4, choiceCount: 2 },
    { level: 3, shapeCount: 5, choiceCount: 3 },
    { level: 4, shapeCount: 6, choiceCount: 3 },
    { level: 5, shapeCount: 7, choiceCount: 4 },
    { level: 6, shapeCount: 8, choiceCount: 4 },
    { level: 7, shapeCount: 9, choiceCount: 4 },
    { level: 8, shapeCount: 10, choiceCount: 5 },
    { level: 9, shapeCount: 11, choiceCount: 5 },
    { level: 10, shapeCount: 12, choiceCount: 6 },
  ],
  alphabet: [
    { level: 1, lettersPerRound: 3, nonConsecutive: false },
    { level: 2, lettersPerRound: 4, nonConsecutive: false },
    { level: 3, lettersPerRound: 5, nonConsecutive: false },
    { level: 4, lettersPerRound: 6, nonConsecutive: false },
    { level: 5, lettersPerRound: 7, nonConsecutive: false },
    { level: 6, lettersPerRound: 7, nonConsecutive: true },
    { level: 7, lettersPerRound: 8, nonConsecutive: true },
    { level: 8, lettersPerRound: 8, nonConsecutive: true },
    { level: 9, lettersPerRound: 9, nonConsecutive: true },
    { level: 10, lettersPerRound: 10, nonConsecutive: true },
  ],
  spelling: [
    { level: 1, minLength: 3, maxLength: 3 },
    { level: 2, minLength: 3, maxLength: 4 },
    { level: 3, minLength: 3, maxLength: 4 },
    { level: 4, minLength: 4, maxLength: 4 },
    { level: 5, minLength: 4, maxLength: 5 },
    { level: 6, minLength: 5, maxLength: 5 },
    { level: 7, minLength: 5, maxLength: 6 },
    { level: 8, minLength: 6, maxLength: 6 },
    { level: 9, minLength: 6, maxLength: 7 },
    { level: 10, minLength: 7, maxLength: 8 },
  ],
  memory: [
    { level: 1, pairs: 4 },
    { level: 2, pairs: 5 },
    { level: 3, pairs: 6 },
    { level: 4, pairs: 6 },
    { level: 5, pairs: 7 },
    { level: 6, pairs: 8 },
    { level: 7, pairs: 9 },
    { level: 8, pairs: 10 },
    { level: 9, pairs: 11 },
    { level: 10, pairs: 12 },
  ],
  division: [
    { level: 1,  maxDivisor: 2,  maxMultiplier: 5,  choiceCount: 4 },
    { level: 2,  maxDivisor: 3,  maxMultiplier: 5,  choiceCount: 4 },
    { level: 3,  maxDivisor: 4,  maxMultiplier: 6,  choiceCount: 4 },
    { level: 4,  maxDivisor: 5,  maxMultiplier: 6,  choiceCount: 4 },
    { level: 5,  maxDivisor: 6,  maxMultiplier: 8,  choiceCount: 4 },
    { level: 6,  maxDivisor: 7,  maxMultiplier: 8,  choiceCount: 4 },
    { level: 7,  maxDivisor: 8,  maxMultiplier: 10, choiceCount: 4 },
    { level: 8,  maxDivisor: 10, maxMultiplier: 10, choiceCount: 4 },
    { level: 9,  maxDivisor: 12, maxMultiplier: 11, choiceCount: 4 },
    { level: 10, maxDivisor: 12, maxMultiplier: 12, choiceCount: 6 },
  ],
  rhyming: [
    { level: 1,  wordLen: 3, choiceCount: 2, tricky: false },
    { level: 2,  wordLen: 3, choiceCount: 2, tricky: false },
    { level: 3,  wordLen: 3, choiceCount: 3, tricky: false },
    { level: 4,  wordLen: 3, choiceCount: 4, tricky: false },
    { level: 5,  wordLen: 4, choiceCount: 4, tricky: false },
    { level: 6,  wordLen: 4, choiceCount: 4, tricky: true  },
    { level: 7,  wordLen: 4, choiceCount: 4, tricky: true  },
    { level: 8,  wordLen: 5, choiceCount: 5, tricky: true  },
    { level: 9,  wordLen: 5, choiceCount: 5, tricky: true  },
    { level: 10, wordLen: 6, choiceCount: 6, tricky: true  },
  ],
  clock: [
    { level: 1,  minuteStep: 60, choiceCount: 2 },
    { level: 2,  minuteStep: 60, choiceCount: 3 },
    { level: 3,  minuteStep: 30, choiceCount: 3 },
    { level: 4,  minuteStep: 30, choiceCount: 4 },
    { level: 5,  minuteStep: 15, choiceCount: 4 },
    { level: 6,  minuteStep: 15, choiceCount: 4 },
    { level: 7,  minuteStep: 10, choiceCount: 4 },
    { level: 8,  minuteStep: 5,  choiceCount: 4 },
    { level: 9,  minuteStep: 5,  choiceCount: 5 },
    { level: 10, minuteStep: 1,  choiceCount: 6 },
  ],
  pattern: [
    { level: 1,  type: 'emoji2',   choiceCount: 2 },
    { level: 2,  type: 'emoji2',   choiceCount: 3 },
    { level: 3,  type: 'emoji3',   choiceCount: 3 },
    { level: 4,  type: 'emoji3',   choiceCount: 4 },
    { level: 5,  type: 'numAdd1',  choiceCount: 4 },
    { level: 6,  type: 'numAdd2',  choiceCount: 4 },
    { level: 7,  type: 'numMul2',  choiceCount: 4 },
    { level: 8,  type: 'numAdd3',  choiceCount: 4 },
    { level: 9,  type: 'numMul3',  choiceCount: 5 },
    { level: 10, type: 'fibonacci', choiceCount: 6 },
  ],
  'english-speaking': [
    { level: 1,  type: 'basic' },
    { level: 2,  type: 'basic' },
    { level: 3,  type: 'basic' },
    { level: 4,  type: 'medium' },
    { level: 5,  type: 'medium' },
    { level: 6,  type: 'medium' },
    { level: 7,  type: 'phrase' },
    { level: 8,  type: 'phrase' },
    { level: 9,  type: 'sentence' },
    { level: 10, type: 'sentence' },
  ],
  compare: [
    { level: 1,  maxNum: 5,    allowEqual: false, timeLimit: 0  },
    { level: 2,  maxNum: 10,   allowEqual: false, timeLimit: 0  },
    { level: 3,  maxNum: 20,   allowEqual: false, timeLimit: 0  },
    { level: 4,  maxNum: 20,   allowEqual: true,  timeLimit: 0  },
    { level: 5,  maxNum: 50,   allowEqual: true,  timeLimit: 0  },
    { level: 6,  maxNum: 50,   allowEqual: true,  timeLimit: 0  },
    { level: 7,  maxNum: 100,  allowEqual: true,  timeLimit: 0  },
    { level: 8,  maxNum: 100,  allowEqual: true,  timeLimit: 0  },
    { level: 9,  maxNum: 500,  allowEqual: true,  timeLimit: 0  },
    { level: 10, maxNum: 1000, allowEqual: true,  timeLimit: 3  },
  ],
};

export const getLevelConfig = (gameName, level) => {
  const configs = LEVEL_CONFIGS[gameName];
  if (!configs) return null;
  return configs[Math.min(Math.max(level, 1), 10) - 1];
};
