export const LEVEL_CONFIGS = {
  addition: [
    { level: 1, maxNum: 5, choiceCount: 4 },
    { level: 2, maxNum: 8, choiceCount: 4 },
    { level: 3, maxNum: 10, choiceCount: 4 },
    { level: 4, maxNum: 15, choiceCount: 4 },
    { level: 5, maxNum: 20, choiceCount: 4 },
    { level: 6, maxNum: 30, choiceCount: 4 },
    { level: 7, maxNum: 50, choiceCount: 4 },
    { level: 8, maxNum: 75, choiceCount: 4 },
    { level: 9, maxNum: 100, choiceCount: 4 },
    { level: 10, maxNum: 100, choiceCount: 6 },
  ],
  'times-tables': [
    { level: 1, maxTable: 3, maxMultiplier: 5, choiceCount: 4 },
    { level: 2, maxTable: 5, maxMultiplier: 6, choiceCount: 4 },
    { level: 3, maxTable: 6, maxMultiplier: 8, choiceCount: 4 },
    { level: 4, maxTable: 7, maxMultiplier: 10, choiceCount: 4 },
    { level: 5, maxTable: 8, maxMultiplier: 10, choiceCount: 4 },
    { level: 6, maxTable: 9, maxMultiplier: 12, choiceCount: 4 },
    { level: 7, maxTable: 10, maxMultiplier: 15, choiceCount: 4 },
    { level: 8, maxTable: 11, maxMultiplier: 15, choiceCount: 4 },
    { level: 9, maxTable: 12, maxMultiplier: 20, choiceCount: 4 },
    { level: 10, maxTable: 12, maxMultiplier: 20, choiceCount: 6 },
  ],
  counting: [
    { level: 1, maxCount: 3, choiceCount: 4 },
    { level: 2, maxCount: 5, choiceCount: 4 },
    { level: 3, maxCount: 8, choiceCount: 4 },
    { level: 4, maxCount: 10, choiceCount: 4 },
    { level: 5, maxCount: 12, choiceCount: 4 },
    { level: 6, maxCount: 15, choiceCount: 4 },
    { level: 7, maxCount: 18, choiceCount: 4 },
    { level: 8, maxCount: 20, choiceCount: 4 },
    { level: 9, maxCount: 25, choiceCount: 4 },
    { level: 10, maxCount: 30, choiceCount: 6 },
  ],
  'color-match': [
    { level: 1, colorCount: 4, choiceCount: 2 },
    { level: 2, colorCount: 5, choiceCount: 3 },
    { level: 3, colorCount: 6, choiceCount: 3 },
    { level: 4, colorCount: 7, choiceCount: 4 },
    { level: 5, colorCount: 8, choiceCount: 4 },
    { level: 6, colorCount: 9, choiceCount: 4 },
    { level: 7, colorCount: 10, choiceCount: 5 },
    { level: 8, colorCount: 11, choiceCount: 5 },
    { level: 9, colorCount: 12, choiceCount: 6 },
    { level: 10, colorCount: 14, choiceCount: 6 },
  ],
  'shape-match': [
    { level: 1, shapeCount: 3, choiceCount: 2 },
    { level: 2, shapeCount: 4, choiceCount: 2 },
    { level: 3, shapeCount: 5, choiceCount: 3 },
    { level: 4, shapeCount: 6, choiceCount: 3 },
    { level: 5, shapeCount: 7, choiceCount: 4 },
    { level: 6, shapeCount: 8, choiceCount: 4 },
    { level: 7, shapeCount: 9, choiceCount: 4 },
    { level: 8, shapeCount: 10, choiceCount: 5 },
    { level: 9, shapeCount: 11, choiceCount: 5 },
    { level: 10, shapeCount: 12, choiceCount: 6 },
  ],
  alphabet: [
    { level: 1, lettersPerRound: 3, nonConsecutive: false },
    { level: 2, lettersPerRound: 4, nonConsecutive: false },
    { level: 3, lettersPerRound: 5, nonConsecutive: false },
    { level: 4, lettersPerRound: 6, nonConsecutive: false },
    { level: 5, lettersPerRound: 7, nonConsecutive: false },
    { level: 6, lettersPerRound: 7, nonConsecutive: true },
    { level: 7, lettersPerRound: 8, nonConsecutive: true },
    { level: 8, lettersPerRound: 8, nonConsecutive: true },
    { level: 9, lettersPerRound: 9, nonConsecutive: true },
    { level: 10, lettersPerRound: 10, nonConsecutive: true },
  ],
  spelling: [
    { level: 1, minLength: 3, maxLength: 3 },
    { level: 2, minLength: 3, maxLength: 4 },
    { level: 3, minLength: 3, maxLength: 4 },
    { level: 4, minLength: 4, maxLength: 4 },
    { level: 5, minLength: 4, maxLength: 5 },
    { level: 6, minLength: 5, maxLength: 5 },
    { level: 7, minLength: 5, maxLength: 6 },
    { level: 8, minLength: 6, maxLength: 6 },
    { level: 9, minLength: 6, maxLength: 7 },
    { level: 10, minLength: 7, maxLength: 8 },
  ],
  memory: [
    { level: 1, pairs: 4 },
    { level: 2, pairs: 5 },
    { level: 3, pairs: 6 },
    { level: 4, pairs: 6 },
    { level: 5, pairs: 7 },
    { level: 6, pairs: 8 },
    { level: 7, pairs: 9 },
    { level: 8, pairs: 10 },
    { level: 9, pairs: 11 },
    { level: 10, pairs: 12 },
  ],
};

export const getLevelConfig = (gameName, level) => {
  const configs = LEVEL_CONFIGS[gameName];
  if (!configs) return null;
  return configs[Math.min(Math.max(level, 1), 10) - 1];
};
